face-recognition-ai/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
face-recognition-ai/face_recognition.py,sha256=s0xQHqhW_ePvVUJVHbVUjtYdd4vCWqgkiMMb-ZOGxJ4,1528
face_recognition_ai/__init__.py,sha256=fcSkql26KgKn2KdlnrTLuN3mWNkh16tMIZUEXJ3cIu8,59
face_recognition_ai/face_recognition.py,sha256=IDLYjdpstDTubxnqHGV0KhiBDIby6Swz3O_pexxr3Ec,3585
face_recognition_ai-0.0.1.dist-info/METADATA,sha256=zg6aKz4-XG8UMvUSsMIu3G8keq8WjcPYOAxEsZE3faw,3646
face_recognition_ai-0.0.1.dist-info/WHEEL,sha256=Xo9-1PvkuimrydujYJAjF7pCkriuXBpUPEjma1nZyJ0,92
face_recognition_ai-0.0.1.dist-info/top_level.txt,sha256=31YrqvblkPP5bjlyvZeY-88xvsL7YUeuAcUBI0XblZs,20
face_recognition_ai-0.0.1.dist-info/RECORD,,
